### ISSUE TITLE
Support for module imports and exports

### ISSUE THREAD

**Issue by niklasmohrin** [wilsonzlin/minify-js#1]
Hey! I came across this project from a panic stacktrace I got when trying to use https://github.com/adamchainz/django-minify-html. Following that, I found that `import` and the different variants of `export` statements are still left as `todo!()`: https://github.com/wilsonzlin/minify-js/blob/eb27a22535a3bbef7c568a597bb7e470f1bc3797/rust/src/emit/mod.rs#L795

I wanted to ask whether support for these statements is planned anytime soon. Are there any particular problems, or has just no one come around to implementing it yet? In that case, I could also try to file a PR myself, it may take some time though. Until then, I already found the option to disable js minification when using `minify-html`

Looking forward to using your library. Thanks!

**Comment by arctic-hen7** [comment]
Any updates on this @wilsonzlin? I'd love to integrate JS minification into [Perseus](https://github.com/framesurge/perseus) (a Rust web development framework), but this issue renders that infeasible at the moment.

**Comment by wilsonzlin** [comment]
I just implemented support in the latest version `0.2.0`, try it out and let me know how it goes. Imports and exports are [quite tricky to implement](https://github.com/wilsonzlin/minify-js/commit/2a2e570e6276ef89ae23dd3f1bb4cafec9491edd), and have some [complex syntax and semantics](https://jakearchibald.com/2021/export-default-thing-vs-thing-as-default/), which is why I've delayed implementing it until now. If there are any issues with the implementation let me know, there's some more polishing I'd like to do in this area.

**Comment by arctic-hen7** [comment]
Fantastic, thank you very much! I'm using this library through `minify-html`, does that need a new version to update for this as well?

**Comment by wilsonzlin** [comment]
Yes, I've just released version `0.10.1` of `minify-html`  which contains the latest `minify-js`.

**Comment by arctic-hen7** [comment]
Perfect, I'll check it out later today!

**Comment by arctic-hen7** [comment]
@wilsonzlin everything's working with the basic examples in my framework now, and the others are running on CI at the moment. Looking great though, much appreciated!

**Comment by wilsonzlin** [comment]
Sounds great, I'll close this issue for now.
